#!/usr/bin/env node
// scripts/seed.mjs — Seeds all candidates and filing deadlines into Supabase
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

// ── Load .env.local ───────────────────────────────────────────
function loadEnv() {
  const path = resolve(__dirname, '../.env.local')
  const env = {}
  for (const line of readFileSync(path, 'utf8').split('\n')) {
    const t = line.trim()
    if (!t || t.startsWith('#')) continue
    const eq = t.indexOf('=')
    if (eq === -1) continue
    env[t.slice(0, eq).trim()] = t.slice(eq + 1).trim()
  }
  return env
}

const env = loadEnv()
const supabaseUrl = env.SUPABASE_URL
const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseKey || supabaseUrl.includes('your-')) {
  console.error('❌ SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set in .env.local')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { persistSession: false }
})

// ── Candidate data ────────────────────────────────────────────
const CANDIDATES = [
  // Senate (1–24)
  { id:1,  name:'Susan Collins',       state:'Maine',          office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'incumbent',           race_competitiveness:'Toss-Up', primary_date:'June 9, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Has broken with party on some climate votes; supported offshore wind. Voted against IRA.',                                                                                                          fossil_fuel_donations:'moderate', fossil_fuel_amount:'$289,469',                 fossil_fuel_cycle:'2020 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/susan-collins/industries?cid=N00000491&cycle=2020', opponent:'Janet Mills (D)' },
  { id:2,  name:'Jon Ossoff',          state:'Georgia',        office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'incumbent',           race_competitiveness:'Toss-Up', primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Voted for IRA. Supports clean energy investment and EV manufacturing in Georgia.',                                                                                                                  fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/jon-ossoff/industries?cid=N00040675&cycle=2026',  opponent:'R primary: Mike Collins, Buddy Carter, Derek Dooley' },
  { id:3,  name:'Roy Cooper',          state:'North Carolina', office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Lean R',  primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'As Governor signed executive orders on clean energy; set 2050 carbon neutrality goals for NC.',                                                                                                          fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SNC2026',                                          opponent:'Michael Whatley (R)' },
  { id:4,  name:'Michael Whatley',     state:'North Carolina', office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'challenger',          race_competitiveness:'Lean R',  primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former RNC Chairman. Trump-endorsed. Limited public climate record.',                                                                                                                                fossil_fuel_donations:'unknown',  fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SNC2026',                                          opponent:'Roy Cooper (D)' },
  { id:5,  name:'Janet Mills',         state:'Maine',          office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Toss-Up', primary_date:'June 9, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'As Maine Governor, set 100% clean electricity goal by 2040. Strong environmental record.',                                                                                                          fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SME2026',                                          opponent:'Susan Collins (R)' },
  { id:6,  name:'Sherrod Brown',       state:'Ohio',           office:'U.S. Senate (Special)', office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Lean R',  primary_date:'May 5, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former Senator; has supported clean energy manufacturing. Mixed fossil fuel record for Ohio.',                                                                                                         fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/sherrod-brown/industries?cid=N00003374&cycle=2024', opponent:'Jon Husted (R)' },
  { id:7,  name:'Jon Husted',          state:'Ohio',           office:'U.S. Senate (Special)', office_type:'us_senate', party:'R', incumbent_status:'incumbent (appointed)',race_competitiveness:'Lean R',  primary_date:'May 5, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Appointed by Gov. DeWine. Supportive of Ohio energy sector including natural gas.',                                                                                                               fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SOH2026',                                          opponent:'Sherrod Brown (D)' },
  { id:8,  name:'Ashley Hinson',       state:'Iowa',           office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'challenger',          race_competitiveness:'Likely R', primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Congresswoman. Supports wind energy (Iowa is major wind state). Opposed carbon pricing.',                                                                                                          fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/ashley-hinson/industries?cid=N00044544&cycle=2024', opponent:'D primary: Zach Wahls (leading), Josh Turek' },
  { id:9,  name:'John Cornyn',         state:'Texas',          office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'incumbent',           race_competitiveness:'Likely R', primary_date:'Mar 3, 2026',   general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Strongly pro-oil & gas. Opposed IRA, climate regulations. Supported LNG exports.',                                                                                                                fossil_fuel_donations:'high',     fossil_fuel_amount:'$4,067,906',              fossil_fuel_cycle:'Career total (through 2020)',   fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/john-cornyn/industries?cid=N00024852',             opponent:'James Talarico (D); Cornyn in R runoff vs. Ken Paxton (May 26)' },
  { id:10, name:'Mark Warner',         state:'Virginia',       office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'incumbent',           race_competitiveness:'Lean D',  primary_date:'June 9, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Voted for IRA. Supports offshore wind off Virginia coast. Climate-focused record.',                                                                                                              fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/mark-warner/industries?cid=N00002097&cycle=2026',  opponent:'David Williams (R)' },
  { id:11, name:'Cory Booker',         state:'New Jersey',     office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'incumbent',           race_competitiveness:'Lean D',  primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Strong climate champion. Co-sponsored Green New Deal. Advocates environmental justice.',                                                                                                          fossil_fuel_donations:'low',      fossil_fuel_amount:'$0',                       fossil_fuel_cycle:'Ongoing',                       fossil_fuel_source:'https://nofossilfuelmoney.org/pledges/',                                                            opponent:'R primary: Alex Zdan (leading), Justin Murphy' },
  { id:12, name:'William Cassidy',     state:'Louisiana',      office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'incumbent',           race_competitiveness:'Safe R',  primary_date:'Nov 3, 2026',   general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Has acknowledged climate science. Supported some coastal restoration. Strong oil & gas ties.',                                                                                                     fossil_fuel_donations:'high',     fossil_fuel_amount:'$1,554,805',              fossil_fuel_cycle:'Career total (through 2020)',   fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/bill-cassidy/industries?cid=N00030245',            opponent:'Julia Letlow (R primary); D primary: Jamie Davis, Nick Albares' },
  { id:13, name:'Ben Ray Luján',       state:'New Mexico',     office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'incumbent',           race_competitiveness:'Lean D',  primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Voted for IRA. Advocates clean energy transition while balancing New Mexico oil economy. Pledged not to take fossil fuel exploration money.',                                                       fossil_fuel_donations:'low',      fossil_fuel_amount:'$0 (fossil fuel exploration)', fossil_fuel_cycle:'Pledge since 2019',            fossil_fuel_source:'https://readsludge.com/2019/04/19/democratic-leader-ben-ray-lujan-endorses-green-new-deal-wont-take-fossil-fuel-exploration-money/', opponent:'No Republican on ballot (disqualified); D primary challenger: Matt Dodson' },
  { id:14, name:'Mary Peltola',        state:'Alaska',         office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Likely R', primary_date:'Aug 25, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former Rep. Supported some resource development while emphasizing environmental protection for Alaska communities.',                                                                                 fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/mary-peltola/industries?cid=N00050780&cycle=2024', opponent:'Dan Sullivan (R, incumbent)' },
  { id:15, name:'Ashley Moody',        state:'Florida',        office:'U.S. Senate (Special)', office_type:'us_senate', party:'R', incumbent_status:'incumbent (appointed)',race_competitiveness:'Lean R',  primary_date:'Aug 18, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Appointed AG turned Senator. Florida faces major climate threats (sea level, hurricanes). Limited proactive climate record.',                                                                      fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SFL2026',                                          opponent:'Alexander Vindman (D)' },
  { id:16, name:'Alexander Vindman',   state:'Florida',        office:'U.S. Senate (Special)', office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Lean R',  primary_date:'Aug 18, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'National security focus. Has cited climate as a national security threat. No detailed legislative climate record.',                                                                                fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SFL2026',                                          opponent:'Ashley Moody (R)' },
  { id:17, name:'John E. Sununu',      state:'New Hampshire',  office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'challenger',          race_competitiveness:'Lean D',  primary_date:'Sept 8, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former Senator. Generally skeptical of climate regulations. Opposes carbon taxes.',                                                                                                                fossil_fuel_donations:'moderate', fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SNH2026',                                          opponent:'Chris Pappas (D)' },
  { id:18, name:'Dan Osborn',          state:'Nebraska',       office:'U.S. Senate',          office_type:'us_senate', party:'I', incumbent_status:'challenger',          race_competitiveness:'Lean R',  primary_date:'May 12, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Independent. Ran strong race in 2024. Labor-focused. Climate position not prominently defined.',                                                                                                    fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SNE2026',                                          opponent:'Pete Ricketts (R, incumbent)' },
  { id:19, name:'James Talarico',      state:'Texas',          office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Likely R', primary_date:'Mar 3, 2026',   general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former Texas state legislator. Progressive climate champion. Co-authored Texas clean energy legislation. Supports aggressive federal climate action and clean energy transition.',               fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=STX2026',                                          opponent:'John Cornyn (R)' },
  { id:20, name:'Ken Paxton',          state:'Texas',          office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'challenger',          race_competitiveness:'Likely R', primary_date:'Mar 3, 2026',   general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former Texas AG. Led multi-state lawsuit against EPA climate regulations. Deeply anti-climate policy. In Republican runoff against Cornyn.',                                                       fossil_fuel_donations:'high',     fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=STX2026',                                          opponent:'John Cornyn (R, primary runoff)' },
  { id:21, name:'Zach Wahls',          state:'Iowa',           office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Likely R', primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Iowa state senator. Supports renewable energy transition, particularly wind. Has backed clean energy investments and climate-aligned agriculture policies.',                                        fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SIA2026',                                          opponent:'Ashley Hinson (R)' },
  { id:22, name:'Chris Pappas',        state:'New Hampshire',  office:'U.S. Senate',          office_type:'us_senate', party:'D', incumbent_status:'challenger',          race_competitiveness:'Lean D',  primary_date:'Sept 8, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former NH Congressman. Supported IRA and clean energy investments. Focused on climate resilience for New England.',                                                                               fossil_fuel_donations:'low',      fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SNH2026',                                          opponent:'John E. Sununu (R)' },
  { id:23, name:'David Williams',      state:'Virginia',       office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'challenger',          race_competitiveness:'Lean D',  primary_date:'June 9, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Virginia politician. Limited public climate record. Expected to oppose Biden-era climate regulations.',                                                                                             fossil_fuel_donations:'unknown',  fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=SVA2026',                                          opponent:'Mark Warner (D)' },
  { id:24, name:'Dan Sullivan',        state:'Alaska',         office:'U.S. Senate',          office_type:'us_senate', party:'R', incumbent_status:'incumbent',           race_competitiveness:'Likely R', primary_date:'Aug 25, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Alaska incumbent. Supports oil and gas development including ANWR. Mixed on climate — has backed some conservation but opposed major climate legislation.',                                      fossil_fuel_donations:'high',     fossil_fuel_amount:null,                       fossil_fuel_cycle:'2026 cycle',                    fossil_fuel_source:'https://www.opensecrets.org/members-of-congress/dan-sullivan/industries?cid=N00035774&cycle=2024', opponent:'Mary Peltola (D)' },

  // Governor (25–36)
  { id:25, name:'Stacey Abrams',       state:'Georgia',        office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Toss-Up', primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Two-time gubernatorial candidate. Strong climate advocate. Supports clean energy economy for Georgia, environmental justice in communities of color, and clean water protections.',          fossil_fuel_donations:'low',      fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GGA2026', opponent:'Burt Jones (R)' },
  { id:26, name:'Andre Dickens',       state:'Georgia',        office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Toss-Up', primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Mayor of Atlanta. Has led Atlanta sustainability initiatives including 100% clean electricity for city operations, EV fleet transition, and urban heat island mitigation.',                  fossil_fuel_donations:'low',      fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GGA2026', opponent:'D primary: Stacey Abrams; general: Burt Jones (R)' },
  { id:27, name:'Burt Jones',          state:'Georgia',        office:'Governor', office_type:'governor', party:'R', incumbent_status:'challenger', race_competitiveness:'Toss-Up', primary_date:'May 19, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Georgia Lt. Governor. Pro-business, pro-natural gas. Has not prioritized climate action. Georgia is a major climate vulnerability state (heat, flooding, drought in south).',             fossil_fuel_donations:'high',     fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GGA2026', opponent:'D primary winner (Abrams or Dickens)' },
  { id:28, name:'Kelly Ayotte',        state:'New Hampshire',  office:'Governor', office_type:'governor', party:'R', incumbent_status:'incumbent',  race_competitiveness:'Lean R',  primary_date:'Sept 8, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Current NH Governor (elected 2024). Former US Senator. Has supported offshore wind permitting and NH clean energy economy. Climate record is pragmatic-moderate.',                     fossil_fuel_donations:'moderate', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GNH2026', opponent:'D candidate TBD' },
  { id:29, name:'Joe Lombardo',        state:'Nevada',         office:'Governor', office_type:'governor', party:'R', incumbent_status:'incumbent',  race_competitiveness:'Lean R',  primary_date:'June 9, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Nevada Governor since 2023. Nevada is a top solar and geothermal state. Has not reversed renewable energy standards but has prioritized economic growth over climate action.',          fossil_fuel_donations:'high',     fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GNV2026', opponent:'D candidate TBD' },
  { id:30, name:'Amy Klobuchar',       state:'Minnesota',      office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Lean D',  primary_date:'Aug 11, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'US Senator considering gubernatorial run. Moderate Democrat. Voted for IRA. Supports clean energy transition, wind energy for Minnesota (top wind state), and climate-resilient agriculture.', fossil_fuel_donations:'moderate', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GMN2026', opponent:'Lisa Demuth (R)' },
  { id:31, name:'Lisa Demuth',         state:'Minnesota',      office:'Governor', office_type:'governor', party:'R', incumbent_status:'challenger', race_competitiveness:'Lean D',  primary_date:'Aug 11, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:"Minnesota House Republican Leader. Has criticized MN clean energy mandates and carbon-free electricity standard. Supports rolling back MN's 2040 100% clean electricity law.",           fossil_fuel_donations:'high',     fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GMN2026', opponent:'Amy Klobuchar (D)' },
  { id:32, name:'Rob Sand',            state:'Iowa',           office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Lean D',  primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:"Iowa State Auditor. Farmer background. Supports clean energy transition for Iowa's agricultural economy, especially wind energy (Iowa is #1 wind state). Advocates for climate-smart farming.", fossil_fuel_donations:'low',  fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GIA2026', opponent:'R primary winner TBD' },
  { id:33, name:'Antonio Villaraigosa',state:'California',     office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Safe D',  primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Former LA Mayor. Has a mixed climate record — championed urban clean energy as mayor but has received oil industry support. Supports CA clean energy standards and EV mandate.',        fossil_fuel_donations:'moderate', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GCA2026', opponent:'D primary: Eleni Kounalakis; general: R candidate TBD' },
  { id:34, name:'Eleni Kounalakis',    state:'California',     office:'Governor', office_type:'governor', party:'D', incumbent_status:'challenger', race_competitiveness:'Safe D',  primary_date:'June 2, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:"CA Lieutenant Governor. Strong climate champion. Fully supports CA climate targets, offshore wind, accelerated clean energy transition, climate adaptation infrastructure, and environmental justice.", fossil_fuel_donations:'low', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GCA2026', opponent:'D primary: Antonio Villaraigosa; general: R candidate TBD' },
  { id:35, name:'Greg Abbott',         state:'Texas',          office:'Governor', office_type:'governor', party:'R', incumbent_status:'incumbent',  race_competitiveness:'Likely R', primary_date:'Mar 3, 2026',   general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Texas Governor since 2015. Strongly pro-oil & gas. Sued Biden administration over climate and energy regulations. Texas leads nation in wind energy — primarily as economic development.', fossil_fuel_donations:'high', fossil_fuel_amount:'$5,000,000+', fossil_fuel_cycle:'Career total', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GTX2026', opponent:'D candidate TBD' },
  { id:36, name:'Ashley Moody',        state:'Florida',        office:'Governor', office_type:'governor', party:'R', incumbent_status:'challenger', race_competitiveness:'Safe R',  primary_date:'Aug 18, 2026',  general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'Previously FL Attorney General. Led multi-state lawsuits against Biden EPA climate regulations. Florida is extremely climate-vulnerable but Moody has not prioritized climate adaptation policy.', fossil_fuel_donations:'moderate', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GFL2026', opponent:'D candidate TBD' },
  { id:37, name:'Kathy Hochul',        state:'New York',       office:'Governor', office_type:'governor', party:'D', incumbent_status:'incumbent',  race_competitiveness:'Safe D',  primary_date:'June 23, 2026', general_date:'Nov 3, 2026', candidacy_status:'declared', known_positions:'NY Governor since 2021. Signed Climate Leadership and Community Protection Act (CLCPA) implementation — one of the most ambitious state climate laws in the US. Set 2030 offshore wind targets, supports congestion pricing to reduce emissions, and has championed environmental justice in disadvantaged communities.', fossil_fuel_donations:'moderate', fossil_fuel_amount:null, fossil_fuel_cycle:'2026 cycle', fossil_fuel_source:'https://www.opensecrets.org/races/industries?id=GNY2026', opponent:'R candidate TBD' },
]

const FILING_DEADLINES = [
  { state:'Alaska',         deadline_date:'2026-06-01', deadline_label:'June 1, 2026',  primary_date:'2026-08-25', notes:'Alaska Division of Elections deadline' },
  { state:'Florida',        deadline_date:'2026-05-08', deadline_label:'May 8, 2026',   primary_date:'2026-08-18', notes:'Special election qualifying period' },
  { state:'Georgia',        deadline_date:'2026-03-06', deadline_label:'Mar 6, 2026',   primary_date:'2026-05-19', notes:'Georgia qualifying closed' },
  { state:'Iowa',           deadline_date:'2026-03-13', deadline_label:'Mar 13, 2026',  primary_date:'2026-06-02', notes:'Iowa Secretary of State deadline' },
  { state:'Louisiana',      deadline_date:'2026-08-14', deadline_label:'Aug 14, 2026',  primary_date:'2026-11-03', notes:'Louisiana jungle primary qualifying' },
  { state:'Maine',          deadline_date:'2026-03-15', deadline_label:'Mar 15, 2026',  primary_date:'2026-06-09', notes:'Maine filing deadline' },
  { state:'Nebraska',       deadline_date:'2026-03-02', deadline_label:'Mar 2, 2026',   primary_date:'2026-05-12', notes:'Nebraska filing closed' },
  { state:'New Hampshire',  deadline_date:'2026-06-12', deadline_label:'June 12, 2026', primary_date:'2026-09-08', notes:'NH filing opens closer to primary' },
  { state:'New Jersey',     deadline_date:'2026-04-06', deadline_label:'Apr 6, 2026',   primary_date:'2026-06-02', notes:'NJ petition deadline' },
  { state:'New Mexico',     deadline_date:'2026-03-10', deadline_label:'Mar 10, 2026',  primary_date:'2026-06-02', notes:'NM filing closed' },
  { state:'North Carolina', deadline_date:'2025-12-19', deadline_label:'Dec 19, 2025',  primary_date:'2026-05-19', notes:'NC filing closed — passed' },
  { state:'Ohio',           deadline_date:'2026-02-20', deadline_label:'Feb 20, 2026',  primary_date:'2026-05-05', notes:'Ohio special election filing closed' },
  { state:'Texas',          deadline_date:'2025-12-09', deadline_label:'Dec 9, 2025',   primary_date:'2026-03-03', notes:'TX filing closed — primary held' },
  { state:'Virginia',       deadline_date:'2026-03-26', deadline_label:'Mar 26, 2026',  primary_date:'2026-06-09', notes:'VA deadline pending' },
]

// ── Main ──────────────────────────────────────────────────────
async function main() {
  console.log(`Connecting to ${supabaseUrl}…\n`)

  // Test connection + check if office_type column exists
  const { data: testRow, error: testErr } = await supabase
    .from('candidates').select('id, office_type').limit(1)

  const tablesExist = !testErr
  const hasOfficeType = tablesExist && testRow !== null

  if (!tablesExist) {
    console.error('❌ Cannot reach candidates table:', testErr.message)
    console.error('\nThe table does not exist yet. Please run supabase/schema.sql')
    console.error('in the Supabase SQL Editor first, then re-run this script.\n')
    process.exit(1)
  }

  console.log('✓ Connected. Upserting candidates…')

  // Upsert all candidates (with office_type)
  const { error: candErr } = await supabase
    .from('candidates')
    .upsert(CANDIDATES, { onConflict: 'id' })

  if (candErr) {
    // If office_type column missing, retry without it for existing rows
    if (candErr.message.includes('office_type')) {
      console.warn('⚠  office_type column missing — upserting without it, then patching…')
      const stripped = CANDIDATES.map(({ office_type, ...rest }) => rest)
      const { error: e2 } = await supabase.from('candidates').upsert(stripped, { onConflict: 'id' })
      if (e2) { console.error('❌ Candidate upsert failed:', e2.message); process.exit(1) }
      console.log('   Rows upserted. Add the office_type column via SQL Editor to enable the Governor filter.')
    } else {
      console.error('❌ Candidate upsert failed:', candErr.message)
      process.exit(1)
    }
  } else {
    console.log(`✓ ${CANDIDATES.length} candidates upserted (24 Senate + 12 Governor)`)
  }

  // Upsert filing deadlines
  console.log('Upserting filing deadlines…')
  const { error: dlErr } = await supabase
    .from('filing_deadlines')
    .upsert(FILING_DEADLINES, { onConflict: 'state' })

  if (dlErr) {
    console.error('❌ Filing deadlines upsert failed:', dlErr.message)
  } else {
    console.log(`✓ ${FILING_DEADLINES.length} filing deadlines upserted`)
  }

  // Verify
  const { count } = await supabase
    .from('candidates').select('*', { count: 'exact', head: true })
  console.log(`\n✅ Done. Total candidates in DB: ${count}`)
}

main().catch(err => { console.error('Fatal:', err); process.exit(1) })
